SUSE-Enceladus/blue-horizon

.gitignore, README.md, app/assets/javascripts/application.js, app/assets/javascripts/sources.js, app/assets/stylesheets/sources.scss, app/controllers/sources_controller.rb, app/helpers/application_helper.rb, app/models/source.rb, app/views/sources/_tabs.html.haml, app/views/sources/edit.html.haml, app/views/sources/index.html.haml, app/views/sources/new.html.haml, config/initializers/blue_horizon.rb, config/initializers/sources.rb, config/locales/en.yml, config/routes.rb, db/migrate/20191025213201_create_sources.rb, db/schema.rb, spec/factories/sources.rb, spec/features/source_editing_spec.rb, spec/fixtures/sources/aks-post-processing.sh, spec/fixtures/sources/external-dns.tf, spec/fixtures/sources/helm.tf, spec/fixtures/sources/k8sresources.tf, spec/fixtures/sources/main.tf, spec/fixtures/sources/nginx-ingress.tf, spec/fixtures/sources/provider.tf, spec/fixtures/sources/variables.tf, spec/models/source_spec.rb
Edit _terraform_ sources in an in-page editor.
=> Sources editor

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/variables.js, app/controllers/clusters_controller.rb, app/controllers/variables_controller.rb, app/helpers/application_helper.rb, app/models/cluster.rb, app/models/source.rb, app/models/variable.rb, app/views/variables/_boolean.html.haml, app/views/variables/_list.html.haml, app/views/variables/_map.html.haml, app/views/variables/_number.html.haml, app/views/variables/_string.html.haml, app/views/variables/show.html.haml, config/locales/en.yml, config/routes.rb, spec/features/cluster_sizing_spec.rb, spec/features/source_editing_spec.rb, spec/features/variable_editing_spec.rb, spec/fixtures/sources/main.tf, spec/fixtures/sources/variables.tf, spec/models/variable_spec.rb, spec/support/helpers.rb
* Terraform scripts are read, parsed, and variables assigned to attributes of a new model.
* Cluster model identifies variables it is responsible for filling.
* Basic types are handled ( from https://www.terraform.io/docs/configuration/variables.html#type-constraints ). Compound types are only handled for string subtype (e.g. `list`, `map`).
=> UI for editing terrrafrom variables

README.md, app/assets/javascripts/sources.js, app/helpers/sources_helper.rb, app/views/sources/edit.html.haml, spec/features/source_editing_spec.rb
re: https://hakiri.io/projects/fd81855786a55b/stacks/c36fe425092dfd/builds/6ab18126460a41/warnings/8f9ff1562875da
=> Move JS function to ruby helper for safety

app/controllers/variables_controller.rb, app/models/variable.rb, spec/models/variable_spec.rb
Moves the default logic out of the controller, to the model
=> Add a convenience function for loading Variable

app/models/cluster.rb, app/models/concerns/exportable.rb, app/models/concerns/saveable.rb, app/models/source.rb, app/models/variable.rb, spec/models/variable_spec.rb
Required some refactoring of concerns.
=> Add a terraform export for variables

app/controllers/sources_controller.rb, app/controllers/variables_controller.rb
Remove export in variables controller
Remove export in sources controller
=> Remove extra exports

app/controllers/welcome_controller.rb, app/helpers/application_helper.rb, app/views/layouts/_sidebar.html.haml, app/views/welcome/index.html.haml, config/initializers/customization.rb, config/locales/en.yml, config/routes.rb, spec/features/welcome_spec.rb
(you can always go back and change your mind)
=> Select a path on the welcome page

.gitignore, .rubocop.yml, README.md, app/assets/config/manifest.js, app/assets/stylesheets/custom.scss, app/helpers/application_helper.rb, app/helpers/sources_helper.rb, app/views/layouts/application.html.haml, app/views/welcome/index.html.haml, config/initializers/customization.rb, config/initializers/locales.rb, config/initializers/navigation.rb, config/initializers/sources.rb, config/locales/custom-en.yml, db/seeds.rb
Clean up some configuration issues, magic strings, and implement a more structured customization framework.
=> Customization

app/assets/javascripts/application.js, app/assets/javascripts/deploys.js, app/controllers/deploys_controller.rb, app/views/deploys/show.html.haml, config/initializers/assets.rb, config/routes.rb, spec/controllers/deploys_controller_spec.rb, spec/rails_helper.rb
Give UI feedback to user of
terraform apply progress.
=> Show deploy feedback

app/assets/stylesheets/sources.scss, app/models/cluster.rb, app/views/clusters/_instance_type_panel.html.haml, app/views/sources/new.html.haml
Position edit source save buttons consistently
Label is consistent between new and edit dialog
also on cluster page changed instance types list to open in new tab
=> Minor styling adjustments to sources page

app/assets/javascripts/plans.js, app/assets/javascripts/sources.js
```
ActionController::RoutingError (No route matches [GET] "/assets/ace/theme-eclipse.js"):
```
=> Resolve error in production due to missing theme assets

.rubocop.yml, Gemfile.development, Gemfile.development.lock, app/assets/javascripts/deploys.js, app/assets/javascripts/plans.js, app/assets/stylesheets/deploys.css, app/assets/stylesheets/plans.css, app/controllers/deploys_controller.rb, app/controllers/plans_controller.rb, app/helpers/application_helper.rb, app/views/deploys/_output.html.haml, app/views/deploys/show.html.haml, app/views/plans/show.html.haml, config/locales/en.yml, config/routes.rb, spec/controllers/deploys_controller_spec.rb, spec/controllers/plans_controller_spec.rb
- Update the templates and logic to render the output
- Stop propagation of polling query
- Show terraform deploy error in UI
This Fixes #38
=> Add introductory steps for plan and deploy

app/assets/stylesheets/custom.scss, app/assets/stylesheets/layout.scss, app/controllers/application_controller.rb, app/controllers/deploys_controller.rb, app/controllers/download_controller.rb, app/controllers/plans_controller.rb, app/helpers/application_helper.rb, app/helpers/authorization_helper.rb, config/locales/en.yml, config/routes.rb, spec/features/authorization_spec.rb, spec/features/welcome_spec.rb, spec/routing/welcome_spec.rb
A simple implementation to guard access to steps until the prequisites are met.
=> Wizard state machine

app/assets/javascripts/variables.js, app/helpers/application_helper.rb, app/helpers/variables_helper.rb, app/views/variables/_password.html.haml, app/views/variables/_string.html.haml, app/views/variables/show.html.haml, config/locales/en.yml, spec/fixtures/sources/variable-mocks.tf.json, spec/models/variable_spec.rb
* Handle any case of 'password' in description
* Peek function
Resolves #51 #66
=> Improvements to password fields

app/assets/javascripts/plans.js, app/controllers/plans_controller.rb, app/views/deploys/show.html.haml, app/views/plans/show.html.haml, config/locales/en.yml, config/routes.rb, spec/controllers/plans_controller_spec.rb
=> Download a plan

app/assets/javascripts/plans.js, app/controllers/plans_controller.rb, app/views/plans/show.html.haml, spec/controllers/plans_controller_spec.rb
- Flash error messages on UI
- No exception when checking if plan exists
This Fixes #56
=> Reset plan when creating one

app/assets/javascripts/deploys.js, app/controllers/deploys_controller.rb
Fix shown error message when it should not.
This Fixes #73
=> Handle error message

app/assets/javascripts/deploys.js
=> Make Next Steps available after deploy

app/assets/javascripts/deploys.js, app/assets/javascripts/plans.js
=> Hide tooltips while running terraform actions

app/assets/javascripts/deploys.js, app/views/deploys/show.html.haml, config/locales/en.yml
add a checkbox to autoscroll the deployment log.
addresses https://github.com/SUSE-Enceladus/blue-horizon/issues/67
=> Add autoscroll option to deployment log

app/assets/javascripts/deploys.js, app/assets/javascripts/plans.js, app/views/deploys/_output.html.haml, spec/controllers/deploys_controller_spec.rb
- Better handling of disabled buttons
- Add buttons on left panel
=> Sync enabling/disabling buttons

app/controllers/sources_controller.rb, app/controllers/variables_controller.rb, app/models/source.rb, app/models/variable.rb, app/services/terraform.rb, spec/controllers/download_controller_spec.rb, spec/controllers/plans_controller_spec.rb, spec/features/authorization_spec.rb, spec/features/cluster_sizing_spec.rb, spec/features/source_editing_spec.rb, spec/features/variable_editing_spec.rb, spec/features/welcome_spec.rb, spec/helpers/authorization_helper_spec.rb, spec/models/source_spec.rb, spec/models/variable_spec.rb, spec/services/terraform_spec.rb
Add terraform validate for
- create and update sources
- load variables
- setup the database
Add terraform class to handle all terraform operations
This Fixes #68
=> Use terraform validate

app/controllers/variables_controller.rb, app/views/variables/show.html.haml, spec/features/variable_editing_spec.rb, spec/fixtures/sources_auth/main.tf, spec/fixtures/sources_auth/variable-mocks-auth-plan.tf.json, spec/fixtures/sources_auth/variables.tf.json, spec/support/helpers.rb
=> Save variables when moving to plan

app/models/source.rb, db/seeds.rb
Handle this as a custom validation function, instead of an after-save callback.
=> Terraform source validation

.rubocop.yml, app/models/concerns/exportable.rb, app/models/source.rb, db/seeds.rb, spec/factories/sources.rb, spec/fixtures/sources_nested/excluded.md, spec/fixtures/sources_nested/main.tf, spec/fixtures/sources_nested/modules/hello/excluded.txt, spec/fixtures/sources_nested/modules/hello/hello.tf, spec/fixtures/sources_nested/modules/hello/variables.tf, spec/fixtures/sources_nested/variables.tf.json, spec/models/source_spec.rb, spec/support/helpers.rb
This enables using terraform sources that are built as modules.
=> Handle relative paths in sources

.bumpversion.cfg, lib/tasks/packaging.rake, packaging/blue-horizon.spec
It's nice to have the custom rake tasks for debugging.
=> Include 'lib' directory in package

app/controllers/sources_controller.rb, app/services/terraform.rb, spec/services/terraform_spec.rb
When making a typo in the scripts,
the validation fails not allowing
to correct it.
This Fixes #111
=> Fix script validation

app/controllers/plans_controller.rb, app/services/terraform.rb, spec/controllers/plans_controller_spec.rb
=> Show terraform plan error in UI

app/controllers/download_controller.rb, spec/controllers/download_controller_spec.rb
=> Properly handle nested output for downloadable zipfile

app/assets/javascripts/deploys.js, app/controllers/deploys_controller.rb, app/services/terraform.rb, app/views/deploys/show.html.haml, config/routes.rb, spec/controllers/deploys_controller_spec.rb
=> Rollback when deployment fails

README.md, app/controllers/clusters_controller.rb, app/models/cluster.rb, config/initializers/customization.rb, db/seeds.rb, dotenv.development.example, spec/features/authorization_spec.rb, spec/features/cluster_sizing_spec.rb, spec/features/welcome_spec.rb
... instead of importing a database key from ENV variable.
Resolves https://github.com/SUSE-Enceladus/blue-horizon/issues/132
=> Specify cloud framework in config

app/controllers/variables_controller.rb
Set cluster labels values to empty when
no there are cluster labels to be added.
This Fixes #136
=> Set cluster_labels to empty

app/assets/javascripts/plans.js, app/services/terraform.rb, spec/controllers/plans_controller_spec.rb
=> Show terraform plan error in JSON format

spec/controllers/deploys_controller_spec.rb, spec/controllers/download_controller_spec.rb, spec/controllers/plans_controller_spec.rb, spec/features/authorization_spec.rb, spec/features/plan_spec.rb, spec/features/source_editing_spec.rb, spec/features/variable_editing_spec.rb, spec/models/source_spec.rb, spec/models/variable_spec.rb, spec/services/terraform_spec.rb, spec/support/helpers.rb
* Move working directory management into helper blocks
* Provide a variable for shorter access to the working path
:metal:
=> DRY up specs

README.md, app/models/variable.rb, app/views/variables/show.html.haml, config/locales/en.yml
* Allow variables to be optionally grouped
* Process group titles through I18N
* Ungrouped variables will not be affected
=> Group variables

README.md
=> Update sqlite doc

app/assets/stylesheets/custom.scss, app/views/variables/_list.html.haml, app/views/variables/_map.html.haml
Prevent empty items from being added to lists & maps, using client-side validation.
BONUS: fix appearance issues with list & map buttons.
=> List, map improvements

config/initializers/session_store.rb
re: https://github.com/rails/rails/issues/35822#issuecomment-607367697
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
=> Add a samesite attribute to cookies

.gitignore, README.md, app/controllers/application_controller.rb, app/controllers/plans_controller.rb, app/helpers/application_helper.rb, app/views/plans/_plan.haml, app/views/plans/show.html.haml, config/initializers/customization.rb, spec/controllers/application_controller_spec.rb, spec/controllers/plans_controller_spec.rb, spec/features/plan_spec.rb, spec/helpers/application_helper_spec.rb
... and set up the Plan view to be friendly for this.
=> Allow views to be overridden with vendor content

README.md, app/assets/stylesheets/override.scss, app/helpers/application_helper.rb, app/views/layouts/application.haml, config/locales/en.yml, spec/features/welcome_spec.rb, spec/features/wrapup_spec.rb
=> Custom top menu items

.gitignore, README.md, app/assets/stylesheets/application.css.erb
Supercedes #177 - thanks @arbulu89 for the concept ... just polishing the edges.
=> Support a vendor-supplied custom style file

app/assets/javascripts/utility.js, app/controllers/plans_controller.rb, app/models/concerns/key_prefixable.rb, app/services/terraform.rb, app/views/clusters/show.html.haml, app/views/deploys/show.html.haml, app/views/plans/show.html.haml, app/views/sources/_tabs.html.haml, app/views/sources/edit.html.haml, app/views/variables/show.html.haml, app/views/welcome/index.html.haml, spec/controllers/plans_controller_spec.rb, spec/features/plan_spec.rb
UI/UX request to remove the 'update plan' button.
The plan will now be regenerated if any variable has changed since terraform was last run (any action).
=> Update the plan if variables have changed since last terraform action

config/application.rb
Let's patch a build and verify this fixes things in OBS before merging.
=> Workaround for workaround for SQLite deprecation
