SUSE-Enceladus/blue-horizon

.travis.yml
Gemfile
Gemfile.lock

I had assumed nodejs as an installation requirement, but this shouldn't be the case.

Use mini_racer as ExecJS backend

---

app/models/cluster.rb
app/models/concerns/key_prefixable.rb
app/models/variable.rb
spec/models/cluster_spec.rb

The Cluster model now uses the same prefixed variables to store it's values as the Variable does; so instance_type and instance_count flow into the Variable attributes.

Cluster model integrates with Variable in Storage

---

app/controllers/plans_controller.rb
spec/controllers/plans_controller_spec.rb

With a normal approach of file + stdout,
it was necessary to add
log_file.sync = true
for an implicit flushing, otherwise, there
were scenarios where not all the info was
written to log file.
This code fix that making use of LogDevice
where file sunchronisation is managed
automatically.

Flush logger

---

app/assets/stylesheets/custom.scss
app/views/layouts/application.html.haml
config/locales/custom-en.yml

Due to content length, footer remains in main content
area regardless of browser width. Footer aligns with
padding for main content area. Background, text color
and link colors updated to match eos specs.
eos footer spec: https://eosdesignsystem.herokuapp.com/layout/footer

Update footer styling to EOS specifications

---

app/assets/stylesheets/custom.scss

The transparent background of the updated footer caused a "floating text" issue on pages that scroll (t wasnt noticeable on non-scrolling pages). This restores a solid background color to the footer, matching the color of the main content panel.

Restore background color to footer

---

app/views/variables/_password.html.haml
app/views/variables/show.html.haml
config/locales/en.yml

Variables with 'password; in the description are rendered as
password type rather than text. The text checked for this is
localized to support description localization without losing
the password check functionality

Update 'password' rendering in variables page

---

app/controllers/plans_controller.rb
spec/controllers/plans_controller_spec.rb

Make sure nothing is left over from a prior run.
Resolves #44

Clean out export dir before running plan.

---

app/assets/javascripts/cluster.js
app/views/clusters/_cluster_size_panel.html.haml
spec/features/cluster_sizing_spec.rb

* Ensure that slider is initialized with the cluster size value
* Call the same events on both textbox changes or slider changes
Resolves #53

Fix some issues with cluster slider sync

---

app/controllers/application_controller.rb
app/controllers/welcome_controller.rb
app/helpers/authorization_helper.rb
app/views/layouts/_locked_session.html.haml
app/views/layouts/application.html.haml
config/locales/en.yml
config/routes.rb
spec/features/authorization_spec.rb

Store the current session ID, pop a modal if another session accesses, but allow the user to unlock the session.
This is a start on https://github.com/SUSE-Enceladus/blue-horizon/issues/84 but I still need to implement some locking around plan & deploy.

Only allow one session at a time

---

README.md
app/helpers/variables_helper.rb
app/views/variables/_string.html.haml
config/locales/en.yml
spec/features/variable_editing_spec.rb
spec/fixtures/sources/variable-mocks.tf.json
spec/helpers/authorization_helper_spec.rb
spec/models/variable_spec.rb

Hi all,
This PR adds the option to create multi select kind of variables. This is really helpful when the terraform scripts has defined set of options for some variables, and we want to make sure that the user will use only the allowed one.
My doubt is if the `get_select_options` method should go in the variables model. Maybe it's better (as `select_type?`)
Here a image with the feature (sorry for the quality, I was not able to make a screenshot as the tab was being hidden all the time...)
@bear454 @jesusbv Could you have a look? If you like the implementation I will add the required UT for the new methods and changes

Create multi select variables layout

---

app/services/terraform.rb

Because `terraform destroy` wasn't run in the export dir, it would fail _if_ the sources use modules (for example, CAP Deployment in EKS).

'rollback' fails if sources have modules

---

README.md
app/helpers/application_helper.rb
app/helpers/variables_helper.rb
spec/features/variable_editing_spec.rb
spec/fixtures/sources/variable-mocks.tf.json

#126 inadvertently broke HTML hyperlinks in description comments, by treating the "//" in "http://..." as a comment marker.
Going back and rethinking, it made more sense to enhance the descriptions by making the hyperlinks active, and alllowing some small markup as well... so I enabled _markdown_ rendering of the descriptions instead, and used HTML comments for unrendered content.
Unfortunately, Redcarpet doesn't handle HTML comments nicely in v3.5.0 ( https://github.com/vmg/redcarpet/issues/692 ), so I had to strip them out before rendering as _markdown_.

Better descriptions

---

README.md
app/helpers/variables_helper.rb
spec/fixtures/sources/variable-mocks.tf.json
spec/helpers/variables_helper_spec.rb

* use case-insensitive non-greedy regex
* remove requirements/handler for quotes around options
* add an error handler
Resolves https://github.com/SUSE-Enceladus/blue-horizon/issues/155

Simplify options handling

---

app/controllers/variables_controller.rb
app/views/variables/show.html.haml
spec/features/variable_editing_spec.rb

Save data and move on to plan by default. If there is a problem, fall back to variables form.
This was the behavior of the 'plan' button anyway; just dropping the redundant 'save' button.

Simplify navigation on variables page

---

README.md
app/models/variable.rb
app/views/variables/_string.html.haml
spec/features/variable_editing_spec.rb
spec/fixtures/sources/variable-mocks.tf.json
spec/helpers/authorization_helper_spec.rb
spec/models/variable_spec.rb

Implement client side variable validation using the pattern option:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern
It adds 2 new options to configure the variables using the description entry;
`[title:my variable title`
`[pattern:[mypattern]:endpattern]`
I have not found a better way to encapsulate the pattern option without the `endpattern` keyword, as the patterns might have several `[]` (even nested ones).

Add client side variables validation

---

spec/support/helpers.rb

This PR proposes a simplification of the RSpec setup.
To allow for inspection of test artifacts after a possibly failed test, the removal of the temporary directory is now performed in the setup phase rather than in the teardown. This required to set the configuration key in a separate step.
In addition to this, the temporary test directory is no longer randomly generated (I couldn't see any reason for this to be actually needed).

simplify test setup and teardown

---

.travis.yml

I noticed in our own fork (where we have terraform sources commited in) that setting up the database before the tests will break the entire build.
Was this step needed in the first place? As far as I could understand, fixtures are imported by the rspec helpers anyway.

Fix Travis runs when sources are present

---

.gitignore
README.md
config/initializers/customization.rb

`CustomHelpers` module, defined in `vendor/lib/custom_helpers.rb` will be added to the `ActionView` load path.

Support a vendor-provided custom view helper module

---

app/helpers/application_helper.rb

Disable html filtering in the markdown render process.
Besides that, I have added an empty vendor stylesheet to use from the vendor folder without modifying the `application.css` file. I don't know if there is a better option, but I have not found it.
This allows markdown entries with html tags. 
Example:
`vendor_custom.css` is modified with the next content to apply new styles to markdown html tags:
```
summary.welcome {
background: #333;
color: #FFF;
border-radius: 3px;
padding: 5px 10px;
outline: none;
}
/* Style the summary when details box is open */
details[open] summary.welcome {
background: #30ba78;
color: #333;
}
```

Enable HTML tags usage in markdown content

---

README.md
app/helpers/application_helper.rb
public/vendor

* use standard markdown syntax
* bypass asset pipeline via `public/` symlink

Allow vendored images

---

app/controllers/deploys_controller.rb
config/locales/en.yml
spec/controllers/deploys_controller_spec.rb

Fix to manage properly the terraform stdout content.
- In the case of an error, the `content` was set with the error message, so it was not getting the correct data to create the progress information. Besides that, the text for failed scenario was not set.
- Rarely, the terraform stdout was coming with `nil` value. The `blank` method adds a safe guard to that scenario, returning an empty progress information.

Fix to manage properly the terraform stdout content in the progress bar

---

app/assets/javascripts/variables.js
app/assets/stylesheets/override.scss
app/views/variables/_string.html.haml

Correct password show/hide styles icon as recommend in the EOS branding:
https://suse.eosdesignsystem.com/form-elements/input-fields
New:
Before:

Correct password show/hide icon styles

---

.travis.yml

Bundler package has been upgraded to `2.2.0` the 10th of December.
https://rubygems.org/gems/bundler/versions/
This has changed our CI and our builds are failing:
https://travis-ci.com/github/SUSE/blue-horizon/jobs/457302257
Changing the bundler arguments to avoid deprecated flags fixes the issue
More info:
https://docs.travis-ci.com/user/languages/ruby/#bundler-20

Define bundler arguments in travis to avoid deprecated flags

---

app/controllers/plans_controller.rb
spec/features/plan_spec.rb

Fix the plan view functionality when it is reached the first one.
If we check the `deploy_path` authorization, the loading gif will stay spinning forever

Fix plan view authorization

---

app/assets/stylesheets/override.scss

The nav buttons look wierd to me, now, without the arrows... and I think most of this is the variance in sizes, so I've tried to mitigate that with a little CSS.
Before
After

Balance the size of the navigation buttons

---

app/controllers/plans_controller.rb
app/views/plans/_error.haml
app/views/plans/show.html.haml
spec/controllers/plans_controller_spec.rb

Fix the error caused during the terraform plan if the authentication (or any terraform plan execution) fails.
https://github.com/SUSE-Enceladus/blue-horizon/issues/195
It sends the error message to the flash and the output to the body.
I have created an additional `_error` view as it is simpler to overwrite if needed (that most probably will happen).
This is the result:
This PR superseds: https://github.com/SUSE-Enceladus/blue-horizon/pull/141

Fix the redirected view on an error during the tf plan

---

README.md
app/assets/javascripts/deploys.js
app/assets/javascripts/index.js
config/environments/production.rb

Some of our JS was written in ES6, which required explicitly activating `Uglifier` in the production environment, in order to compress assets. Uglifier requires node.js, so this forced node to be a dependency in production.
In reality,all the assets are precompiled, so we shouldn't need any asset pipeline components in production.
In order to get back to this state, ES6 code was machine translated, via Babel, to ES5, then the original compressor command restored.

Eliminate unexpected production requirement of nodejs for assets

---

app/controllers/plans_controller.rb

Just removing one line of code that I added by mistake.
The truth is that it doesn't impact the app, as the line cannot be executed (the file is always deleted in the `cleanup` method that is executed always before this).
PD:
And the test coverage was not even affected as even the code in the `if` side is not executed, checking the conditions makes the coverage catch this line...

Remove delete operation in plan as it is not executed
